# Dockerfile cronjob and automatic chromadb update

FROM python:3.1-slim

WORKDIR /app

# Install dependencies (this layer is cached)
RUN pip install --no-cache-dir \
    azure-storage-blob \
    chromadb \
    langchain \
    langchain-community \
    sentence-transformers \
    beautifulsoup4 \
    PyPDF2 \
    pypdf \
    requests \
    lxml

# Copy your scripts
COPY src/data/ingestion.py .
COPY src/data/vectorstore.py .
COPY src/utils/config.py .

# Default command runs both scripts
CMD ["bash", "-c", "python3 ingestion.py && python3 vectorstore.py"]