apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Production Let's Encrypt server
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email for urgent renewal and security notices
    email: vivupadi@gmail.com  
    # Secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Use HTTP-01 challenge
    solvers:
    - http01:
        ingress:
          class: nginx
